import { INodeProperties } from 'n8n-workflow';

export const projectOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['project'] } },
		options: [
			{ name: 'Get Many', value: 'getMany', description: 'Get projects from the workspace', action: 'Get many projects' },
			{ name: 'Get', value: 'get', description: 'Get a single project by ID', action: 'Get a project' },
			{ name: 'Create', value: 'create', description: 'Create one or more projects (async – returns ticketId)', action: 'Create a project' },
			{ name: 'Update', value: 'update', description: 'Update one or more projects (async – returns ticketId)', action: 'Update a project' },
			{ name: 'Delete', value: 'delete', description: 'Delete a project', action: 'Delete a project' },
			{ name: 'Archive', value: 'archive', description: 'Archive a project (async – returns ticketId)', action: 'Archive a project' },
			{ name: 'Unarchive', value: 'unarchive', description: 'Restore an archived project (async – returns ticketId)', action: 'Unarchive a project' },
			{ name: 'Create From Template', value: 'createFromTemplate', description: 'Create a project based on a template', action: 'Create a project from template' },
			{ name: 'Update Master Data From Template', value: 'updateMasterDataFromTemplate', description: 'Apply template master data to an existing project', action: 'Update project master data from template' },
		],
		default: 'getMany',
	},
];

export const projectFields: INodeProperties[] = [
	// ─── Get Many ────────────────────────────────────────────────────────────
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['project'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Project IDs (comma-separated)', name: 'projectIds', type: 'string', default: '' },
			{ displayName: 'Language', name: 'lang', type: 'string', default: 'de-DE' },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'W. Europe Standard Time' },
			{ displayName: 'View ID', name: 'viewId', type: 'string', default: '' },
			{ displayName: 'Include Tags In Archived', name: 'includeTagsInArchived', type: 'boolean', default: false },
		],
	},

	// ─── Get single ──────────────────────────────────────────────────────────
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['get', 'delete', 'archive', 'unarchive'] } },
		description: 'The GUID of the project',
	},

	// ─── Create ──────────────────────────────────────────────────────────────
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['create'] } },
	},
	{
		displayName: 'Phase ID (Project Folder)',
		name: 'phaseId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['project'], operation: ['create'] } },
		description: 'Numeric ID of the project folder',
	},
	{
		displayName: 'Type ID (Project Type)',
		name: 'typeId',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['project'], operation: ['create'] } },
		description: 'Numeric ID of the project type',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['project'], operation: ['create'] } },
		options: [
			{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Goal', name: 'goal', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Benefit', name: 'benefit', type: 'string', default: '' },
			{ displayName: 'Start Date', name: 'startDate', type: 'dateTime', default: '' },
			{ displayName: 'End Date', name: 'endDate', type: 'dateTime', default: '' },
			{ displayName: 'Budget', name: 'budget', type: 'number', default: 0 },
			{ displayName: 'Currency', name: 'currency', type: 'options', options: [{ name: 'EUR', value: 'EUR' }, { name: 'USD', value: 'USD' }, { name: 'CHF', value: 'CHF' }, { name: 'CAD', value: 'CAD' }, { name: 'GBP', value: 'GBP' }, { name: 'AUD', value: 'AUD' }], default: 'EUR' },
			{ displayName: 'Department ID', name: 'departmentId', type: 'number', default: 0 },
			{ displayName: 'Location ID', name: 'locationId', type: 'number', default: 0 },
			{ displayName: 'Project Manager (email or ID)', name: 'projectManager', type: 'string', default: '' },
			{ displayName: 'Status ID', name: 'statusId', type: 'number', default: 0 },
			{ displayName: 'Workflow ID', name: 'workflowId', type: 'number', default: 0 },
			{ displayName: 'Hourly Rate', name: 'hourlyRate', type: 'number', default: 0 },
			{ displayName: 'Use Personal Hourly Rates', name: 'usePersonalHourlyRates', type: 'boolean', default: false },
			{ displayName: 'Block Time Recording', name: 'blockTimeRecording', type: 'boolean', default: false },
			{ displayName: 'External ID', name: 'externalId', type: 'string', default: '' },
			{ displayName: 'No Feed', name: 'noFeed', type: 'boolean', default: false },
			{ displayName: 'Timezone ID', name: 'timezoneId', type: 'string', default: 'W. Europe Standard Time' },
		],
	},

	// ─── Update ──────────────────────────────────────────────────────────────
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['update'] } },
		description: 'The GUID of the project to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['project'], operation: ['update'] } },
		options: [
			{ displayName: 'Title', name: 'title', type: 'string', default: '' },
			{ displayName: 'Description', name: 'description', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Goal', name: 'goal', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Benefit', name: 'benefit', type: 'string', default: '' },
			{ displayName: 'Start Date', name: 'startDate', type: 'dateTime', default: '' },
			{ displayName: 'End Date', name: 'endDate', type: 'dateTime', default: '' },
			{ displayName: 'Budget', name: 'budget', type: 'number', default: 0 },
			{ displayName: 'Currency', name: 'currency', type: 'string', default: '' },
			{ displayName: 'Phase ID', name: 'phaseId', type: 'number', default: 0 },
			{ displayName: 'Type ID', name: 'typeId', type: 'number', default: 0 },
			{ displayName: 'Department ID', name: 'departmentId', type: 'number', default: 0 },
			{ displayName: 'Location ID', name: 'locationId', type: 'number', default: 0 },
			{ displayName: 'Project Manager', name: 'projectManager', type: 'string', default: '' },
			{ displayName: 'Status ID', name: 'statusId', type: 'number', default: 0 },
			{ displayName: 'Hourly Rate', name: 'hourlyRate', type: 'number', default: 0 },
			{ displayName: 'Use Personal Hourly Rates', name: 'usePersonalHourlyRates', type: 'boolean', default: false },
			{ displayName: 'Block Time Recording', name: 'blockTimeRecording', type: 'boolean', default: false },
			{ displayName: 'Parent ID', name: 'parentId', type: 'string', default: '' },
		],
	},

	// ─── Create From Template ─────────────────────────────────────────────────
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['createFromTemplate'] } },
		description: 'The GUID of the project template',
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['createFromTemplate'] } },
	},
	{
		displayName: 'Folder (Project Folder Name)',
		name: 'folder',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['createFromTemplate'] } },
		description: 'Name of the project folder (phaseId equivalent for template creation)',
	},
	{
		displayName: 'Project Type (Name)',
		name: 'projectType',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['createFromTemplate'] } },
	},
	{
		displayName: 'Additional Options',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['project'], operation: ['createFromTemplate'] } },
		options: [
			{ displayName: 'Is Private', name: 'isPrivate', type: 'boolean', default: false },
			{ displayName: 'Start Date', name: 'startDate', type: 'dateTime', default: '' },
			{ displayName: 'Status ID', name: 'statusId', type: 'number', default: 0 },
			{ displayName: 'Code (Project Code)', name: 'code', type: 'string', default: '' },
			{ displayName: 'Import: Tasks', name: 'optTasks', type: 'boolean', default: true },
			{ displayName: 'Import: Flavors', name: 'optFlavors', type: 'boolean', default: true },
			{ displayName: 'Import: Budget', name: 'optBudget', type: 'boolean', default: true },
			{ displayName: 'Import: Description', name: 'optDescription', type: 'boolean', default: true },
			{ displayName: 'Import: Manager', name: 'optManager', type: 'boolean', default: true },
			{ displayName: 'Import: Permissions', name: 'optPermissions', type: 'boolean', default: true },
			{ displayName: 'Adjust Task Dates', name: 'optAdjustTaskDates', type: 'boolean', default: true },
		],
	},

	// ─── Update Master Data From Template ────────────────────────────────────
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['updateMasterDataFromTemplate'] } },
		description: 'The GUID of the project template',
	},
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['project'], operation: ['updateMasterDataFromTemplate'] } },
		description: 'The GUID of the project to update',
	},
	{
		displayName: 'Fields to Apply',
		name: 'templateApplyFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['project'], operation: ['updateMasterDataFromTemplate'] } },
		options: [
			{ displayName: 'Overwrite Existing Values', name: 'overwriteValues', type: 'boolean', default: false },
			{ displayName: 'Apply: Start Date', name: 'startDate', type: 'boolean', default: false },
			{ displayName: 'Apply: End Date', name: 'endDate', type: 'boolean', default: false },
			{ displayName: 'Apply: Flavors', name: 'flavors', type: 'boolean', default: false },
			{ displayName: 'Apply: Labels', name: 'labels', type: 'boolean', default: false },
			{ displayName: 'Apply: Manager', name: 'manager', type: 'boolean', default: false },
			{ displayName: 'Apply: Budget', name: 'budget', type: 'boolean', default: false },
			{ displayName: 'Apply: Location', name: 'location', type: 'boolean', default: false },
			{ displayName: 'Apply: Description', name: 'description', type: 'boolean', default: false },
			{ displayName: 'Apply: Goal', name: 'goal', type: 'boolean', default: false },
			{ displayName: 'Apply: Benefit', name: 'benefit', type: 'boolean', default: false },
		],
	},
];
