import { INodeProperties } from 'n8n-workflow';

export const settingsOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['settings'] } },
		options: [
			{ name: 'Get Timezones', value: 'getTimezones', description: 'Get all supported timezone IDs', action: 'Get timezones' },
			{ name: 'Get Status Ticket', value: 'getStatusTicket', description: 'Poll the result of an async operation by ticket ID', action: 'Get status ticket' },
			{ name: 'Get Members', value: 'getMembers', description: 'Get member settings for the workspace', action: 'Get member settings' },
			{ name: 'Update Member', value: 'updateMember', description: 'Update member settings / flavors (async)', action: 'Update member' },
			{ name: 'Get Absence Types', value: 'getAbsenceTypes', description: 'Get all absence types', action: 'Get absence types' },
			{ name: 'Get Absence Type', value: 'getAbsenceType', description: 'Get a single absence type by ID', action: 'Get absence type' },
			{ name: 'Create Absence Types', value: 'createAbsenceType', description: 'Create absence types (async)', action: 'Create absence type' },
			{ name: 'Update Absence Types', value: 'updateAbsenceType', description: 'Update absence types (async)', action: 'Update absence type' },
			{ name: 'Delete Absence Type', value: 'deleteAbsenceType', description: 'Delete an absence type', action: 'Delete absence type' },
			{ name: 'Get Working Times (All)', value: 'getAllWorkingTimes', description: 'Get working time records for all members', action: 'Get all working times' },
			{ name: 'Get Working Times (User)', value: 'getUserWorkingTimes', description: 'Get working time records for a specific user', action: 'Get user working times' },
			{ name: 'Create Working Times', value: 'createWorkingTime', description: 'Create working time records (async)', action: 'Create working time' },
			{ name: 'Update Working Times', value: 'updateWorkingTime', description: 'Update working time records (async)', action: 'Update working time' },
			{ name: 'Delete Working Time', value: 'deleteWorkingTime', description: 'Delete a working time record', action: 'Delete working time' },
			{ name: 'Invite Members', value: 'inviteMembers', description: 'Invite users to the workspace', action: 'Invite members' },
			{ name: 'Invite Guests', value: 'inviteGuests', description: 'Invite guests to the workspace', action: 'Invite guests' },
		],
		default: 'getTimezones',
	},
];

export const settingsFields: INodeProperties[] = [
	// ─── Status Ticket ────────────────────────────────────────────────────────
	{
		displayName: 'Ticket ID',
		name: 'ticketId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['getStatusTicket'] } },
		description: 'The ticket ID returned by an async operation',
	},

	// ─── Members ─────────────────────────────────────────────────────────────
	{
		displayName: 'Options',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['getMembers'] } },
		options: [
			{ displayName: 'Language', name: 'lang', type: 'string', default: 'de-DE' },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'W. Europe Standard Time' },
		],
	},
	{
		displayName: 'Member ID or Email',
		name: 'memberId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['updateMember'] } },
	},
	{
		displayName: 'Flavors (JSON Array)',
		name: 'flavorJson',
		type: 'json',
		default: '[{"target":"FlavorName","value":"FlavorValue"}]',
		displayOptions: { show: { resource: ['settings'], operation: ['updateMember'] } },
		description: 'Array of {target, value} objects for member flavors',
	},

	// ─── Absence Types ────────────────────────────────────────────────────────
	{
		displayName: 'Options',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['getAbsenceTypes', 'getAbsenceType'] } },
		options: [
			{ displayName: 'Language', name: 'lang', type: 'string', default: 'de-DE' },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'W. Europe Standard Time' },
		],
	},
	{
		displayName: 'Absence Type ID',
		name: 'absenceTypeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['getAbsenceType', 'deleteAbsenceType'] } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['createAbsenceType'] } },
	},
	{
		displayName: 'Type',
		name: 'absenceTypeLimitType',
		type: 'options',
		options: [{ name: 'Limited (with yearly budget)', value: 'limited' }, { name: 'Unlimited', value: 'unlimited' }],
		default: 'unlimited',
		displayOptions: { show: { resource: ['settings'], operation: ['createAbsenceType'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['createAbsenceType'] } },
		options: [
			{ displayName: 'Is Approval Necessary', name: 'isApprovalNecessary', type: 'boolean', default: false },
			{ displayName: 'Include In Holidays Overview', name: 'includeInHolidaysOverview', type: 'boolean', default: true },
			{ displayName: 'Yearly Budget (days)', name: 'yearlyBudget', type: 'number', default: 0 },
			{ displayName: 'Recommended Approvers (emails)', name: 'recommendedApprovers', type: 'string', default: '' },
			{ displayName: 'External ID', name: 'externalId', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Absence Type ID',
		name: 'absenceTypeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['updateAbsenceType'] } },
	},
	{
		displayName: 'Use External ID',
		name: 'useExternalId',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['settings'], operation: ['updateAbsenceType'] } },
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['updateAbsenceType'] } },
		options: [
			{ displayName: 'Title', name: 'title', type: 'string', default: '' },
			{ displayName: 'Type', name: 'type', type: 'options', options: [{ name: 'Limited', value: 'limited' }, { name: 'Unlimited', value: 'unlimited' }], default: 'unlimited' },
			{ displayName: 'Is Approval Necessary', name: 'isApprovalNecessary', type: 'boolean', default: false },
			{ displayName: 'Include In Holidays Overview', name: 'includeInHolidaysOverview', type: 'boolean', default: true },
			{ displayName: 'Yearly Budget', name: 'yearlyBudget', type: 'number', default: 0 },
			{ displayName: 'Recommended Approvers', name: 'recommendedApprovers', type: 'string', default: '' },
		],
	},

	// ─── Working Times ────────────────────────────────────────────────────────
	{
		displayName: 'Options',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['getAllWorkingTimes', 'getUserWorkingTimes'] } },
		options: [
			{ displayName: 'Language', name: 'lang', type: 'string', default: 'de-DE' },
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'W. Europe Standard Time' },
		],
	},
	{
		displayName: 'User ID or Email',
		name: 'userId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['getUserWorkingTimes', 'createWorkingTime'] } },
	},
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['createWorkingTime'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['createWorkingTime'] } },
		options: [
			{ displayName: 'End Date', name: 'endDate', type: 'dateTime', default: '' },
			{ displayName: 'Monday (min)', name: 'mondayCapacity', type: 'number', default: 480 },
			{ displayName: 'Tuesday (min)', name: 'tuesdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Wednesday (min)', name: 'wednesdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Thursday (min)', name: 'thursdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Friday (min)', name: 'fridayCapacity', type: 'number', default: 480 },
			{ displayName: 'Saturday (min)', name: 'saturdayCapacity', type: 'number', default: 0 },
			{ displayName: 'Sunday (min)', name: 'sundayCapacity', type: 'number', default: 0 },
			{ displayName: 'External ID', name: 'externalId', type: 'string', default: '' },
			{ displayName: 'Timezone ID', name: 'timezoneId', type: 'string', default: 'W. Europe Standard Time' },
		],
	},
	{
		displayName: 'Daily Capacity ID',
		name: 'dailyCapacityId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['updateWorkingTime', 'deleteWorkingTime'] } },
		description: 'The GUID of the daily capacity record',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['settings'], operation: ['updateWorkingTime'] } },
		options: [
			{ displayName: 'Start Date', name: 'startDate', type: 'dateTime', default: '' },
			{ displayName: 'End Date', name: 'endDate', type: 'dateTime', default: '' },
			{ displayName: 'Monday (min)', name: 'mondayCapacity', type: 'number', default: 480 },
			{ displayName: 'Tuesday (min)', name: 'tuesdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Wednesday (min)', name: 'wednesdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Thursday (min)', name: 'thursdayCapacity', type: 'number', default: 480 },
			{ displayName: 'Friday (min)', name: 'fridayCapacity', type: 'number', default: 480 },
			{ displayName: 'Saturday (min)', name: 'saturdayCapacity', type: 'number', default: 0 },
			{ displayName: 'Sunday (min)', name: 'sundayCapacity', type: 'number', default: 0 },
			{ displayName: 'Use External ID', name: 'useExternalId', type: 'boolean', default: false },
			{ displayName: 'Timezone ID', name: 'timezoneId', type: 'string', default: 'W. Europe Standard Time' },
		],
	},

	// ─── Invite ───────────────────────────────────────────────────────────────
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['settings'], operation: ['inviteMembers', 'inviteGuests'] } },
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		required: true,
		options: [
			{ name: 'Admin', value: 'admin' },
			{ name: 'Member', value: 'member' },
			{ name: 'Restricted Member', value: 'restricted-member' },
			{ name: 'Read-only Member', value: 'read-only-member' },
		],
		default: 'member',
		displayOptions: { show: { resource: ['settings'], operation: ['inviteMembers'] } },
	},
	{
		displayName: 'Role',
		name: 'role',
		type: 'options',
		required: true,
		options: [
			{ name: 'Guest', value: 'guest' },
			{ name: 'Restricted Guest', value: 'restricted-guest' },
			{ name: 'Read-only Guest', value: 'read-only-guest' },
		],
		default: 'guest',
		displayOptions: { show: { resource: ['settings'], operation: ['inviteGuests'] } },
	},
	{
		displayName: 'Locale',
		name: 'locale',
		type: 'options',
		options: [{ name: 'German (de)', value: 'de' }, { name: 'English (en)', value: 'en' }],
		default: 'de',
		displayOptions: { show: { resource: ['settings'], operation: ['inviteMembers', 'inviteGuests'] } },
	},
];
