import { INodeProperties } from 'n8n-workflow';

export const statusReportOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['statusReport'] } },
		options: [
			{ name: 'Create', value: 'create', description: 'Create status reports (async – returns ticketId)', action: 'Create a status report' },
			{ name: 'Update', value: 'update', description: 'Update status reports (async – returns ticketId)', action: 'Update a status report' },
			{ name: 'Delete', value: 'delete', description: 'Delete a status report', action: 'Delete a status report' },
			{ name: 'Create From Template', value: 'createFromTemplate', description: 'Create a status report from a template', action: 'Create status report from template' },
		],
		default: 'create',
	},
];

export const statusReportFields: INodeProperties[] = [
	// ─── Create ──────────────────────────────────────────────────────────────
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['create'] } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['create'] } },
	},
	{
		displayName: 'Status Date',
		name: 'statusDate',
		type: 'dateTime',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['create'] } },
	},
	{
		displayName: 'Overall Status',
		name: 'overallStatusId',
		type: 'options',
		required: true,
		options: [
			{ name: '1 – Green', value: 1 },
			{ name: '2 – Yellow', value: 2 },
			{ name: '3 – Red', value: 3 },
			{ name: '4 – On Hold', value: 4 },
			{ name: '5 – Not Started', value: 5 },
			{ name: '6 – Completed', value: 6 },
			{ name: '7 – Cancelled', value: 7 },
		],
		default: 1,
		displayOptions: { show: { resource: ['statusReport'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['statusReport'], operation: ['create'] } },
		options: [
			{ displayName: 'Explanation', name: 'explanation', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Next Steps', name: 'nextSteps', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Target Date', name: 'targetDate', type: 'dateTime', default: '' },
			{ displayName: 'Time Status ID (1-4)', name: 'timeStatusId', type: 'number', default: 0 },
			{ displayName: 'Cost Status ID (1-4)', name: 'costStatusId', type: 'number', default: 0 },
			{ displayName: 'Goal Status ID (1-4)', name: 'goalStatusId', type: 'number', default: 0 },
			{ displayName: 'Progress Manual (0–100)', name: 'progressManual', type: 'number', default: 0 },
			{ displayName: 'Is Published', name: 'isPublished', type: 'boolean', default: false },
			{ displayName: 'External ID', name: 'externalId', type: 'string', default: '' },
			{ displayName: 'No Feed', name: 'noFeed', type: 'boolean', default: false },
			{ displayName: 'Timezone ID', name: 'timezoneId', type: 'string', default: 'W. Europe Standard Time' },
		],
	},

	// ─── Update ──────────────────────────────────────────────────────────────
	{
		displayName: 'Status Report ID',
		name: 'statusReportId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['update'] } },
	},
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['update'] } },
	},
	{
		displayName: 'Use External ID',
		name: 'useExternalId',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['statusReport'], operation: ['update'] } },
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['statusReport'], operation: ['update'] } },
		options: [
			{ displayName: 'Title', name: 'title', type: 'string', default: '' },
			{ displayName: 'Explanation', name: 'explanation', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Next Steps', name: 'nextSteps', type: 'string', typeOptions: { rows: 3 }, default: '' },
			{ displayName: 'Status Date', name: 'statusDate', type: 'dateTime', default: '' },
			{ displayName: 'Target Date', name: 'targetDate', type: 'dateTime', default: '' },
			{ displayName: 'Overall Status ID (1-7)', name: 'overallStatusId', type: 'number', default: 0 },
			{ displayName: 'Time Status ID (1-4)', name: 'timeStatusId', type: 'number', default: 0 },
			{ displayName: 'Cost Status ID (1-4)', name: 'costStatusId', type: 'number', default: 0 },
			{ displayName: 'Goal Status ID (1-4)', name: 'goalStatusId', type: 'number', default: 0 },
			{ displayName: 'Progress Manual (0–100)', name: 'progressManual', type: 'number', default: 0 },
			{ displayName: 'Is Published', name: 'isPublished', type: 'boolean', default: false },
			{ displayName: 'Timezone ID', name: 'timezoneId', type: 'string', default: 'W. Europe Standard Time' },
		],
	},

	// ─── Delete ──────────────────────────────────────────────────────────────
	{
		displayName: 'Status Report ID',
		name: 'statusReportId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['delete'] } },
	},

	// ─── Create From Template ─────────────────────────────────────────────────
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['createFromTemplate'] } },
	},
	{
		displayName: 'Project ID',
		name: 'projectId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['createFromTemplate'] } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['statusReport'], operation: ['createFromTemplate'] } },
	},
	{
		displayName: 'Progress Manual (0–100)',
		name: 'progressManual',
		type: 'number',
		required: true,
		default: 0,
		displayOptions: { show: { resource: ['statusReport'], operation: ['createFromTemplate'] } },
	},
];
